apiVersion: apps/v1
kind: Deployment
metadata:
  name: gubernator
  labels:
    app: gubernator
spec:
  replicas: 4
  selector:
    matchLabels:
      app: gubernator
  template:
    metadata:
      labels:
        app: gubernator
    spec:
      serviceAccountName: gubernator
      containers:
        - image: ghcr.io/mailgun/gubernator:latest
          imagePullPolicy: IfNotPresent
          ports:
            - name: http-port
              containerPort: 80
          name: gubernator
          env:
          - name: GUBER_K8S_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: GUBER_K8S_POD_IP
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
          # Must set the HTTP addresses, as gubernator
          # defaults to listening on localhost only
          - name: GUBER_HTTP_ADDRESS
            value: 0.0.0.0:80
          # Use the k8s API for peer discovery
          - name: GUBER_PEER_DISCOVERY_TYPE
            value: "k8s"
          # This should match the port number HTTP is listening on
          # as defined by `containerPort`
          - name: GUBER_K8S_POD_PORT
            value: "81"
          # The selector used when listing endpoints. This selector
          # should only select gubernator peers.
          - name: GUBER_K8S_ENDPOINTS_SELECTOR
            value: "app=gubernator"
          # Gubernator can watch 'endpoints' for changes to the peers
          # or it can watch 'pods' (Defaults to 'endpoints')
          # - name: GUBER_K8S_WATCH_MECHANISM
          #  value: "endpoints"
          # Enable debug for diagnosing issues
          - name: GUBER_DEBUG
            value: "true"

      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: gubernator
  labels:
    app: gubernator
spec:
  clusterIP: None
  #- name: http-port
  #targetPort: 80
  #protocol: TCP
  #port: 80
  selector:
    app: gubernator
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: gubernator
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: get-endpoints
rules:
- apiGroups:
  - ""
  resources:
  - endpoints
  verbs:
  - list
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: get-endpoints
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: get-endpoints
subjects:
- kind: ServiceAccount
  name: gubernator
