apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "gubernator.fullname" . }}
  labels:
  {{- include "gubernator.labels" . | nindent 4 }}
  annotations:
  {{- include "gubernator.annotations" . | nindent 4 }}

spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "gubernator.fullname" . }}
  minReplicas: {{ .Values.gubernator.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.gubernator.autoscaling.maxReplicas }}
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.gubernator.autoscaling.cpuAverageUtilization }}
