# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: peers.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import ratelimit_pb2 as ratelimit__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='peers.proto',
  package='pb.gubernator',
  syntax='proto3',
  serialized_options=_b('Z\002pb\200\001\001'),
  serialized_pb=_b('\n\x0bpeers.proto\x12\rpb.gubernator\x1a\x0fratelimit.proto\"L\n\x14PeerRateLimitRequest\x12\x34\n\x0brate_limits\x18\x01 \x03(\x0b\x32\x1f.pb.gubernator.RateLimitRequest\"N\n\x15PeerRateLimitResponse\x12\x35\n\x0brate_limits\x18\x01 \x03(\x0b\x32 .pb.gubernator.RateLimitResponse2p\n\x0cPeersService\x12`\n\x11GetPeerRateLimits\x12#.pb.gubernator.PeerRateLimitRequest\x1a$.pb.gubernator.PeerRateLimitResponse\"\x00\x42\x07Z\x02pb\x80\x01\x01\x62\x06proto3')
  ,
  dependencies=[ratelimit__pb2.DESCRIPTOR,])




_PEERRATELIMITREQUEST = _descriptor.Descriptor(
  name='PeerRateLimitRequest',
  full_name='pb.gubernator.PeerRateLimitRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='rate_limits', full_name='pb.gubernator.PeerRateLimitRequest.rate_limits', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=47,
  serialized_end=123,
)


_PEERRATELIMITRESPONSE = _descriptor.Descriptor(
  name='PeerRateLimitResponse',
  full_name='pb.gubernator.PeerRateLimitResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='rate_limits', full_name='pb.gubernator.PeerRateLimitResponse.rate_limits', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=125,
  serialized_end=203,
)

_PEERRATELIMITREQUEST.fields_by_name['rate_limits'].message_type = ratelimit__pb2._RATELIMITREQUEST
_PEERRATELIMITRESPONSE.fields_by_name['rate_limits'].message_type = ratelimit__pb2._RATELIMITRESPONSE
DESCRIPTOR.message_types_by_name['PeerRateLimitRequest'] = _PEERRATELIMITREQUEST
DESCRIPTOR.message_types_by_name['PeerRateLimitResponse'] = _PEERRATELIMITRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

PeerRateLimitRequest = _reflection.GeneratedProtocolMessageType('PeerRateLimitRequest', (_message.Message,), dict(
  DESCRIPTOR = _PEERRATELIMITREQUEST,
  __module__ = 'peers_pb2'
  # @@protoc_insertion_point(class_scope:pb.gubernator.PeerRateLimitRequest)
  ))
_sym_db.RegisterMessage(PeerRateLimitRequest)

PeerRateLimitResponse = _reflection.GeneratedProtocolMessageType('PeerRateLimitResponse', (_message.Message,), dict(
  DESCRIPTOR = _PEERRATELIMITRESPONSE,
  __module__ = 'peers_pb2'
  # @@protoc_insertion_point(class_scope:pb.gubernator.PeerRateLimitResponse)
  ))
_sym_db.RegisterMessage(PeerRateLimitResponse)


DESCRIPTOR._options = None

_PEERSSERVICE = _descriptor.ServiceDescriptor(
  name='PeersService',
  full_name='pb.gubernator.PeersService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=205,
  serialized_end=317,
  methods=[
  _descriptor.MethodDescriptor(
    name='GetPeerRateLimits',
    full_name='pb.gubernator.PeersService.GetPeerRateLimits',
    index=0,
    containing_service=None,
    input_type=_PEERRATELIMITREQUEST,
    output_type=_PEERRATELIMITRESPONSE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_PEERSSERVICE)

DESCRIPTOR.services_by_name['PeersService'] = _PEERSSERVICE

# @@protoc_insertion_point(module_scope)
