gubernator:

  fullnameOverride: {}
  nameOverride: {}
  priorityClassName: {}

  autoscaling:
    enabled: true
    minReplicas: 2
    maxReplicas: 10
    cpuAverageUtilization: 50

  replicaCount: 4

  image:
    repository: ghcr.io/mailgun/gubernator
    pullPolicy: IfNotPresent

    # By default tag is overriding appVersion from .Chart.yaml
    tag: "latest"

  labels:
    a: "b"

  # Enabling gubernator debugger, default false
  # debug: true

  # Defines the mechanism to discover new pods
  # default is endpoints
  # watchPods: true

  server:
    http:
      port: "80"

  annotations: { }

  serviceAccount:
    create: false
#    name: "teste"

  nodeSelector: {}

  resources:
    requests:
      cpu: 100m
      memory: 150Mi

  serviceMonitor:
    create: false
    interval: 5s
    scrapeTimeout: 5s