#! /bin/sh

# Make sure the script fails fast.
set -e
set -u
set -x

PROTO_DIR=./proto

# Cleanup outdated autogenerated files.
rm -f $PROTO_DIR/*.go

protoc -I=$PROTO_DIR \
    --go_out=plugins=grpc:$PROTO_DIR \
    $PROTO_DIR/*.proto