"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file

Copyright 2018-2022 Mailgun Technologies Inc

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
"""
import abc
import grpc
from gubernator import gubernator_pb2

class V1Stub:
    def __init__(self, channel: grpc.Channel) -> None: ...
    GetRateLimits: grpc.UnaryUnaryMultiCallable[
        gubernator_pb2.GetRateLimitsReq,
        gubernator_pb2.GetRateLimitsResp,
    ]
    """Given a list of rate limit requests, return the rate limits of each."""
    HealthCheck: grpc.UnaryUnaryMultiCallable[
        gubernator_pb2.HealthCheckReq,
        gubernator_pb2.HealthCheckResp,
    ]
    """This method is for round trip benchmarking and can be used by
    the client to determine connectivity to the server
    """

class V1Servicer(metaclass=abc.ABCMeta):
    @abc.abstractmethod
    def GetRateLimits(
        self,
        request: gubernator_pb2.GetRateLimitsReq,
        context: grpc.ServicerContext,
    ) -> gubernator_pb2.GetRateLimitsResp:
        """Given a list of rate limit requests, return the rate limits of each."""
    @abc.abstractmethod
    def HealthCheck(
        self,
        request: gubernator_pb2.HealthCheckReq,
        context: grpc.ServicerContext,
    ) -> gubernator_pb2.HealthCheckResp:
        """This method is for round trip benchmarking and can be used by
        the client to determine connectivity to the server
        """

def add_V1Servicer_to_server(servicer: V1Servicer, server: grpc.Server) -> None: ...
