// Code generated by protoc-gen-go. DO NOT EDIT.
// source: common.proto

/*
Package pb is a generated protocol buffer package.

It is generated from these files:
	common.proto
	ratelimit.proto

It has these top-level messages:
	RateLimitDuration
	RateLimitRequest
	RateLimitResponse
	RateLimitKeyRequest
	Descriptor
	DescriptorStatus
*/
package pb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// Defines a rate limit duration and requests per duration
type RateLimitDuration struct {
	// The number of requests that can occur for the duration of the rate limit
	Requests int64 `protobuf:"varint,1,opt,name=requests" json:"requests,omitempty"`
	// The duration of the rate limit in milliseconds
	// Second = 1000 Milliseconds
	// Minute = 60000 Milliseconds
	// Hour = 3600000 Milliseconds
	Duration int64 `protobuf:"varint,2,opt,name=duration" json:"duration,omitempty"`
}

func (m *RateLimitDuration) Reset()                    { *m = RateLimitDuration{} }
func (m *RateLimitDuration) String() string            { return proto.CompactTextString(m) }
func (*RateLimitDuration) ProtoMessage()               {}
func (*RateLimitDuration) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *RateLimitDuration) GetRequests() int64 {
	if m != nil {
		return m.Requests
	}
	return 0
}

func (m *RateLimitDuration) GetDuration() int64 {
	if m != nil {
		return m.Duration
	}
	return 0
}

func init() {
	proto.RegisterType((*RateLimitDuration)(nil), "pb.gubernator.RateLimitDuration")
}

func init() { proto.RegisterFile("common.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 116 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x49, 0xce, 0xcf, 0xcd,
	0xcd, 0xcf, 0xd3, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x2d, 0x48, 0xd2, 0x4b, 0x2f, 0x4d,
	0x4a, 0x2d, 0xca, 0x4b, 0x2c, 0xc9, 0x2f, 0x52, 0xf2, 0xe6, 0x12, 0x0c, 0x4a, 0x2c, 0x49, 0xf5,
	0xc9, 0xcc, 0xcd, 0x2c, 0x71, 0x29, 0x2d, 0x4a, 0x2c, 0xc9, 0xcc, 0xcf, 0x13, 0x92, 0xe2, 0xe2,
	0x28, 0x4a, 0x2d, 0x2c, 0x4d, 0x2d, 0x2e, 0x29, 0x96, 0x60, 0x54, 0x60, 0xd4, 0x60, 0x0e, 0x82,
	0xf3, 0x41, 0x72, 0x29, 0x50, 0x75, 0x12, 0x4c, 0x10, 0x39, 0x18, 0xdf, 0x89, 0x25, 0x8a, 0xa9,
	0x20, 0x29, 0x89, 0x0d, 0x6c, 0x91, 0x31, 0x20, 0x00, 0x00, 0xff, 0xff, 0x2e, 0x4c, 0x86, 0xe5,
	0x78, 0x00, 0x00, 0x00,
}
